### ISSUE TITLE
link seems to be broken (404 Not Found error) 

### ISSUE THREAD

**Issue by PavelKotov1** [am0nsec/HellsGate#6]
Link to the paper: https://vxug.fakedoma.in/papers/hells-gate.pdf seems to be broken.
Could you please update the link?
Thanks in advance!

**Comment by am0nsec** [comment]
I'm not managing the website so I can't help here. 
But the PDF is on the repository [here](https://github.com/am0nsec/HellsGate/blob/master/hells-gate.pdf).
